user { "jas",
loginShell => '/bin/bash',
uidNumber => '500',
gidNumber => '100',
realname => 'James de Assis Silva',
homeDirectory => '/home/jas',
userPassword => 'e2NyeXB0fTUwN1o4dnIzcmJBaVE=',
}
user { "leon",
loginShell => '/bin/bash',
uidNumber => '501',
gidNumber => '100',
realname => 'Leonardo Gregory Brunnet',
homeDirectory => '/home/leon',
userPassword => 'e2NyeXB0fWJJL0VhMThNN3JXZkk=',
}
user { "skoliveira",
loginShell => '/bin/bash',
uidNumber => '503',
gidNumber => '100',
realname => 'Samuel Oliveira',
homeDirectory => '/home/skoliveira',
userPassword => 'e1NTSEF9ZHR1ZElvQUZMeE94MUJTTXRVOWVXR1JBWE5ITmtnOVk=',
}
user { "melo",
loginShell => '/bin/bash',
uidNumber => '504',
gidNumber => '100',
realname => 'Ricardo Melo Ferreira, 129442, M203',
homeDirectory => '/home/melo',
userPassword => 'e2NyeXB0fTJoemZPRlhMWHIyVC4=',
}
user { "rizzato",
loginShell => '/bin/bash',
uidNumber => '505',
gidNumber => '100',
realname => 'Felipe Barbedo Rizzato, Prof, N211',
homeDirectory => '/home/rizzato',
userPassword => 'e1NTSEF9TW9Hc3VYeXVOWjh2UUs1QnJxa1E5bGt4UmFyRHhreVc=',
}
user { "magusmao",
loginShell => '/bin/bash',
uidNumber => '506',
gidNumber => '100',
realname => 'Miguel Gusmao, Prof, N213',
homeDirectory => '/home/magusmao',
userPassword => 'e2NyeXB0fUYxNEFlL3JMUjVJNWs=',
}
user { "esalcedo",
loginShell => '/bin/bash',
uidNumber => '507',
gidNumber => '100',
realname => 'Evy Augusto Salcedo Torres',
homeDirectory => '/home/esalcedo',
userPassword => 'e2NyeXB0fTBDQ2NNMTVrc1BlQXc=',
}
user { "arenzon",
loginShell => '/bin/bash',
uidNumber => '508',
gidNumber => '100',
realname => 'Jeferson Jacob Arenzon',
homeDirectory => '/home/arenzon',
userPassword => 'e1NTSEF9OWpTMTR4K0RkUHdLUmRCeC9EYTdySFEwOWhxdzRlNks=',
}
user { "caca",
loginShell => '/bin/bash',
uidNumber => '509',
gidNumber => '100',
realname => 'Carolina Brito',
homeDirectory => '/home/caca',
userPassword => 'e2NyeXB0fTVGUzNGSmRndXEyQWs=',
}
user { "barbosa",
loginShell => '/bin/bash',
uidNumber => '510',
gidNumber => '100',
realname => 'Marcia C Barbosa',
homeDirectory => '/home/barbosa',
userPassword => 'e2NyeXB0fTYxeUp1U0NPNzJTYVE=',
}
user { "idiart",
loginShell => '/bin/bash',
uidNumber => '511',
gidNumber => '100',
realname => 'Marco Aurelio Idiart',
homeDirectory => '/home/idiart',
userPassword => 'e1NTSEF9UEkzT3hDRnhQK2RpWHk2NmozZEZqNHNvNDROK2FUQ3c=',
}
user { "glt",
loginShell => '/bin/bash',
uidNumber => '512',
gidNumber => '100',
realname => 'Gilberto Lima Tomas',
homeDirectory => '/home/glt',
userPassword => 'e2NyeXB0fUxLSHFPOFhtMm1WOVk=',
}
user { "tmarcelo",
loginShell => '/bin/bash',
uidNumber => '513',
gidNumber => '100',
realname => 'T Marcelo',
homeDirectory => '/home/tmarcelo',
userPassword => 'e1NTSEF9YnBhY1VjMXJUVFR3c2hNREtMcjZ3WDRHQjZZNm1TVi8=',
}
user { "oliveira",
loginShell => '/bin/bash',
uidNumber => '514',
gidNumber => '100',
realname => 'Alan Barros de Oliveira',
homeDirectory => '/home/oliveira',
userPassword => 'e1NTSEF9bmNzK3JwRVhqZGZzR2pTMmNpNkJIMlRQK3p4Rlh0MC8=',
}
user { "ziebell",
loginShell => '/bin/bash',
uidNumber => '515',
gidNumber => '100',
realname => 'Luis Fernando Ziebell',
homeDirectory => '/home/ziebell',
userPassword => 'e2NyeXB0fVV3UUNNdHMzbkY4eVU=',
}
user { "rubem",
loginShell => '/bin/bash',
uidNumber => '516',
gidNumber => '100',
realname => 'Rubem Erichsen Junior',
homeDirectory => '/home/rubem',
userPassword => 'e2NyeXB0fS5VQ0pZc01SbzZld00=',
}
user { "julio",
loginShell => '/bin/bash',
uidNumber => '517',
gidNumber => '100',
realname => 'Julio',
homeDirectory => '/home/julio',
userPassword => 'e1NTSEF9YTlHUG94VTBzdEdIK3hidzVyRzNVcW1rdXY4WUhhREU=',
}
user { "srisau",
loginShell => '/bin/bash',
uidNumber => '518',
gidNumber => '100',
realname => 'srisau',
homeDirectory => '/home/srisau',
userPassword => 'e1NTSEF9ZGdnS0RXcXlEUERjSjY4RkVVKzVra1RPOFhBM0xyZ3Q=',
}
user { "matemich",
loginShell => '/bin/bash',
uidNumber => '519',
gidNumber => '100',
realname => 'matemich',
homeDirectory => '/home/matemich',
userPassword => 'e1NTSEF9UUovVDhlSlVUNU56cEtrUUc4em55VllFbTEvaSthLys=',
}
user { "nicolao",
loginShell => '/bin/bash',
uidNumber => '520',
gidNumber => '100',
realname => 'Lucas Nicolao',
homeDirectory => '/home/nicolao',
userPassword => 'e2NyeXB0fS5yL3FVZE50WjlYZ28=',
}
user { "linelb",
loginShell => '/bin/bash',
uidNumber => '521',
gidNumber => '100',
realname => 'Aline Lopes Balladares',
homeDirectory => '/home/linelb',
userPassword => 'e1NTSEF9MzVLL2p4YmQzbE41eUdubkRjM09Id2ZLV2tjaVF5U0k=',
}
user { "joqa",
loginShell => '/bin/bash',
uidNumber => '522',
gidNumber => '100',
realname => 'Joacir',
homeDirectory => '/home/joqa',
userPassword => 'e1NTSEF9MDM0QkV4RkMxK2tXdDJPRGpJMmREZ0lrNFFmdHNOcFI=',
}
user { "adriana",
loginShell => '/bin/bash',
uidNumber => '523',
gidNumber => '100',
realname => 'Adriana',
homeDirectory => '/home/adriana',
userPassword => 'e1NTSEF9em1CeU1oSGtNL3BzRU51VjB3RHRMYzU1MDRyTmlXaWQ=',
}
user { "diehl",
loginShell => '/bin/bash',
uidNumber => '524',
gidNumber => '100',
realname => 'Alexandre Diehl',
homeDirectory => '/home/diehl',
userPassword => 'e1NTSEF9dE5RdjBOQlBBWHJtSmZIOVlUL3dKNmdtbjJ2djBOcjg=',
}
user { "henrique",
loginShell => '/bin/bash',
uidNumber => '525',
gidNumber => '100',
realname => 'Henrique Marks',
homeDirectory => '/home/henrique',
userPassword => 'e1NTSEF9VGpWS1hya2dXM09kN2pJY1V6OTRId092c1UxNTBkNE8=',
}
user { "colla",
loginShell => '/bin/bash',
uidNumber => '526',
gidNumber => '100',
realname => 'Thiago Escobar Colla',
homeDirectory => '/home/colla',
userPassword => 'e1NTSEF9N1RQUjZlWTVuc1QwenpBOHRaN3pWMVpBU1VCb1VwbDk=',
}
user { "rita",
loginShell => '/bin/bash',
uidNumber => '527',
gidNumber => '100',
realname => 'Rita Maria Cunha de Almeida',
homeDirectory => '/home/rita',
userPassword => 'e1NTSEF9Z1A0S01vZjNIVTNJMzRUNnB0SEZFZHovNlBSclM3em4=',
}
user { "heitor",
loginShell => '/bin/bash',
uidNumber => '528',
gidNumber => '100',
realname => 'Heitor Carpes Marques Fernandes',
homeDirectory => '/home/heitor',
userPassword => 'e2NyeXB0fWI1SEQ2Yml0c0luNWM=',
}
user { "calovi",
loginShell => '/bin/bash',
uidNumber => '529',
gidNumber => '100',
realname => 'Daniel Calovi',
homeDirectory => '/home/calovi',
userPassword => 'e2NyeXB0fTdrdnl0R0JlZ2NSc1E=',
}
user { "raul",
loginShell => '/bin/bash',
uidNumber => '530',
gidNumber => '100',
realname => 'Raul Carlos Fadanelli Filho',
homeDirectory => '/home/raul',
userPassword => 'e1NTSEF9dE9vK2tnb3QyQVpxaG0wTndzSllGZUNpSEk2UG16akI=',
}
user { "gio",
loginShell => '/bin/bash',
uidNumber => '531',
gidNumber => '100',
realname => 'Glaucius Iahnke de Oliveira',
homeDirectory => '/home/gio',
userPassword => 'e1NTSEF9ZWQvUi9VYnl2dVpJVTNlRElZendVd1RrcmNRWUhGRVg=',
}
user { "aluisio",
loginShell => '/bin/bash',
uidNumber => '532',
gidNumber => '100',
realname => 'Aluisio de Andrade',
homeDirectory => '/home/aluisio',
userPassword => 'e1NTSEF9UDhxeGZJOGVkMzU3UHZvaTF4cnh1U0c0K0I1Z3djZDM=',
}
user { "wsjr",
loginShell => '/bin/bash',
uidNumber => '533',
gidNumber => '100',
realname => 'Wilson Simeoni Jr',
homeDirectory => '/home/wsjr',
userPassword => 'e2NyeXB0fXZtQ3Q0TUV5MlRFSWM=',
}
user { "pakter",
loginShell => '/bin/bash',
uidNumber => '534',
gidNumber => '100',
realname => 'Renato Pakter',
homeDirectory => '/home/pakter',
userPassword => 'e1NTSEF9KzJ1LzIwMTN0SllCak8rREVUQ3loQlBpckF5aFRwaTY=',
}
user { "cbonatto",
loginShell => '/bin/bash',
uidNumber => '535',
gidNumber => '100',
realname => 'C Bonatto',
homeDirectory => '/home/cbonatto',
userPassword => 'e1NTSEF9Z2F1a1NyRDJjM25FcjA5Z1dZWUVPNG1zSXNYQUhOYXY=',
}
user { "agderivi",
loginShell => '/bin/bash',
uidNumber => '536',
gidNumber => '100',
realname => 'Alexandre Derivi',
homeDirectory => '/home/agderivi',
userPassword => 'e1NTSEF9SURuMFRiVnVmdEJ4RkZFZnRuNSt5encyUU5vV2V2TWs=',
}
user { "mpinto",
loginShell => '/bin/bash',
uidNumber => '537',
gidNumber => '100',
realname => 'Mauricio Pinto',
homeDirectory => '/home/mpinto',
userPassword => 'e1NTSEF9VXNuZ0NWcGJmMzBRckErYUI1dkkwaGNIZXkwNUtsSjQ=',
}
user { "abonatto",
loginShell => '/bin/bash',
uidNumber => '538',
gidNumber => '100',
realname => 'Alexandre Bonatto',
homeDirectory => '/home/abonatto',
userPassword => 'e1NTSEF9MzBaVGpPcGw1eU8vUjM2UzdnbmV2Q1M3WlJ6S3BQZEg=',
}
user { "sebas",
loginShell => '/bin/bash',
uidNumber => '539',
gidNumber => '100',
realname => 'Sebastian Goncalves',
homeDirectory => '/home/sebas',
userPassword => 'e1NTSEF9WHNSS2hKWnRzTzU1ZzJHUmVsb0lhSFlUclVXckNub1o=',
}
user { "rlink",
loginShell => '/bin/bash',
uidNumber => '540',
gidNumber => '100',
realname => 'Rodrigo Link Federizzi',
homeDirectory => '/home/rlink',
userPassword => 'e1NTSEF9SEs5SlNoNkkyeXNGbTJSZEsrR3VHSlloVFNZL3BPSDg=',
}
user { "marfcg",
loginShell => '/bin/bash',
uidNumber => '541',
gidNumber => '100',
realname => 'Marcelo Ferreira da Costa Gomes',
homeDirectory => '/home/marfcg',
userPassword => 'e2NyeXB0fUZrZUt6TjE2bS8zUkU=',
}
user { "thielo",
loginShell => '/bin/bash',
uidNumber => '542',
gidNumber => '100',
realname => 'Marcelo Thielo',
homeDirectory => '/home/thielo',
userPassword => 'e1NTSEF9MkxROVczS1d3S3ZEWWl5R1dtVXEzT1A3Q3pKNmpBTWU=',
}
user { "fmetz",
loginShell => '/bin/bash',
uidNumber => '543',
gidNumber => '100',
realname => 'Fernando Lucas Metz',
homeDirectory => '/home/fmetz',
userPassword => 'e1NTSEF9LzhGaUdSL3FIUjlRb2dCT0FVYWRua2VEb3JBYllGSkw=',
}
user { "aendler",
loginShell => '/bin/bash',
uidNumber => '544',
gidNumber => '100',
realname => 'antonio endler',
homeDirectory => '/home/aendler',
userPassword => 'e1NTSEF9M3RMV0pFd3poYmR3d1BCY3pLNm1rUCs0ZzJMYjVjQTQ=',
}
user { "agenor",
loginShell => '/bin/bash',
uidNumber => '545',
gidNumber => '100',
realname => 'Agenor Hentz da Silva Jr',
homeDirectory => '/home/agenor',
userPassword => 'e1NTSEF9ZzQyKzk5WldrM0ZPZ3I5OVNDOGw1dXFRRDZ2blJ4RlQ=',
}
user { "roncaratti",
loginShell => '/bin/bash',
uidNumber => '546',
gidNumber => '100',
realname => 'luiz fernando roncaratti jr',
homeDirectory => '/home/roncaratti',
userPassword => 'e1NTSEF9TVdPMVZQT0tjdmFkS0dtdm80SnM4YlZFUVR6NXR3Rjg=',
}
user { "chris",
loginShell => '/bin/bash',
uidNumber => '547',
gidNumber => '100',
realname => 'Christopher Thomas',
homeDirectory => '/home/chris',
userPassword => 'e1NTSEF9NUVVcXZtTmtWbnZuS0taTTBQbk1KdzFTMzhCZlFXZ04=',
}
user { "eneves",
loginShell => '/bin/bash',
uidNumber => '548',
gidNumber => '100',
realname => 'Eduardo Barros Neves',
homeDirectory => '/home/eneves',
userPassword => 'e1NTSEF9ODNhU0xUYzBNd0kzWTR2dXBhMXZMVitnVm1uYlJoR28=',
}
user { "everton",
loginShell => '/bin/bash',
uidNumber => '549',
gidNumber => '100',
realname => 'Everton Agnes',
homeDirectory => '/home/everton',
userPassword => 'e2NyeXB0fTg2c0lOaDBVb2FJcVU=',
}
user { "rejane",
loginShell => '/bin/bash',
uidNumber => '550',
gidNumber => '100',
realname => 'Rejane',
homeDirectory => '/home/rejane',
userPassword => 'e1NTSEF9RnRDYXZlQ3ZHdGcwTS9RRTVFRzUwTmRCTUtrQ2FZSy8=',
}
user { "mpoloureiro",
loginShell => '/bin/bash',
uidNumber => '551',
gidNumber => '100',
realname => 'Marcos Paulo',
homeDirectory => '/home/mpoloureiro',
userPassword => 'e1NTSEF9ZGNtbHB3QTI1TWRCU0hUMWFWb2NYWXkvQkRzQ1UvL24=',
}
user { "rogerpn",
loginShell => '/bin/bash',
uidNumber => '552',
gidNumber => '100',
realname => 'Roger Pizzato Nunes',
homeDirectory => '/home/rogerpn',
userPassword => 'e1NTSEF9R0J0enhaVk5OeFlDS2tsRytBdVhiYWt0TzNKYUdKbGg=',
}
user { "cmoura",
loginShell => '/bin/bash',
uidNumber => '553',
gidNumber => '100',
realname => 'Cassio Stein Moura',
homeDirectory => '/home/cmoura',
userPassword => 'e1NTSEF9K3RHWEZ0MjA1UW0xbkdpdWdQSEFuREQ5cFBGeVN1Y2Q=',
}
user { "billoni",
loginShell => '/bin/bash',
uidNumber => '554',
gidNumber => '100',
realname => 'Orlando Vito Billoni',
homeDirectory => '/home/billoni',
userPassword => 'e1NTSEF9cXJZMnF1aXBhV01EV0cvS3RWVERHUVd6Y2xtYnBhWVI=',
}
user { "zerocool",
loginShell => '/bin/bash',
uidNumber => '555',
gidNumber => '100',
realname => 'Jose Luiz Rybarczyk Filho',
homeDirectory => '/home/zerocool',
userPassword => 'e2NyeXB0fUtKb0h5LjMzZlAuYkk=',
}
user { "tarcisio",
loginShell => '/bin/bash',
uidNumber => '556',
gidNumber => '100',
realname => 'Tarcisio Nunes Teles',
homeDirectory => '/home/tarcisio',
userPassword => 'e1NTSEF9b2tETThQN2hQYmhreEtCNy9xTjJpZ2gzVjdsVjVGQk0=',
}
user { "bonacina",
loginShell => '/bin/bash',
uidNumber => '557',
gidNumber => '100',
realname => 'Tiago Luis Bonacina',
homeDirectory => '/home/bonacina',
userPassword => 'e1NTSEF9RGlOeUE3SVg3YmFxeE1ac3hMZ2ttWVR3VnppTE9jWG8=',
}
user { "italo",
loginShell => '/bin/bash',
uidNumber => '558',
gidNumber => '100',
realname => 'italo gabriel neide',
homeDirectory => '/home/italo',
userPassword => 'e2NyeXB0fThKQ0ZmSEh5SC5Oc00=',
}
user { "ismael",
loginShell => '/bin/bash',
uidNumber => '559',
gidNumber => '100',
realname => 'Ismael Fortuna',
homeDirectory => '/home/ismael',
userPassword => 'e2NyeXB0fXQvQUI5cDRGeWZ6eWs=',
}
user { "carine",
loginShell => '/bin/bash',
uidNumber => '560',
gidNumber => '100',
realname => 'carine beatrici',
homeDirectory => '/home/carine',
userPassword => 'e2NyeXB0fVM3MW9wc2E0c3NieTI=',
}
user { "avill",
loginShell => '/bin/bash',
uidNumber => '561',
gidNumber => '100',
realname => 'Aline Villavicencio',
homeDirectory => '/home/avill',
userPassword => 'e1NTSEF9ZXV5RkNvb29zbFVrZkZKQVhoMFJ4blkyK0VnWnVyRXc=',
}
user { "lasalcedo",
loginShell => '/bin/bash',
uidNumber => '562',
gidNumber => '100',
realname => 'Luiz Alberto Salcedo',
homeDirectory => '/home/lasalcedo',
userPassword => 'e1NTSEF9SVB5YUx2THdqQzQ3T0pTY0paR2lHYjUvblllM0J6OHk=',
}
user { "jonathas",
loginShell => '/bin/bash',
uidNumber => '563',
gidNumber => '100',
realname => 'Jonathas Nunes da Silva',
homeDirectory => '/home/jonathas',
userPassword => 'e2NyeXB0fTZ1OHdySExxSzdKNlE=',
}
user { "szortyka",
loginShell => '/bin/bash',
uidNumber => '564',
gidNumber => '100',
realname => 'Marcia Szortyka',
homeDirectory => '/home/szortyka',
userPassword => 'e2NyeXB0fS5XS2Q2bXQucUk1S1k=',
}
user { "tiberio",
loginShell => '/bin/bash',
uidNumber => '565',
gidNumber => '100',
realname => 'Tiberio Borges Vale',
homeDirectory => '/home/tiberio',
userPassword => 'e1NTSEF9TVlZcFJEc0RnVnBZZUhZTm9CUHJxcXBqT2VrbWZ3dEo=',
}
user { "samoel",
loginShell => '/bin/bash',
uidNumber => '566',
gidNumber => '100',
realname => 'Samoel Renan Mello da Silva',
homeDirectory => '/home/samoel',
userPassword => 'e2NyeXB0fUZ1L1BIU3JtVGo5bmM=',
}
user { "rgaelzer",
loginShell => '/bin/bash',
uidNumber => '567',
gidNumber => '100',
realname => 'Rudi Gaelzer',
homeDirectory => '/home/rgaelzer',
userPassword => 'e1NTSEF9dk1qS09aRE5HRU0vd3RQZUFYMVFvM0VvUGZKSFB2eHk=',
}
user { "israel",
loginShell => '/bin/bash',
uidNumber => '568',
gidNumber => '100',
realname => 'Israel',
homeDirectory => '/home/israel',
userPassword => 'e1NTSEF9bERJNnozNlYxMGsxK04rcXdYL3lHeWNSQlY4bkNucVM=',
}
user { "iglesias",
loginShell => '/bin/bash',
uidNumber => '569',
gidNumber => '100',
realname => 'Jose Roberto Iglesias',
homeDirectory => '/home/iglesias',
userPassword => 'e1NTSEF9TCt0MXVrOHFoSlowNW1DNnI0RzdQT1lSRGtrMy9nN0k=',
}
user { "ney",
loginShell => '/bin/bash',
uidNumber => '570',
gidNumber => '100',
realname => 'Ney Marcal',
homeDirectory => '/home/ney',
userPassword => 'e1NTSEF9aHpFKzhvMHU5RU1YMUFQMXk4MTBYSGltVmR3VVNiNGc=',
}
user { "edgar",
loginShell => '/bin/bash',
uidNumber => '571',
gidNumber => '100',
realname => 'Edgar Santos',
homeDirectory => '/home/edgar',
userPassword => 'e1NTSEF9Qm45aWhWYkhMaEdkeXd2a25OWDNxTVhuTU0reXdUWE0=',
}
user { "alechand",
loginShell => '/bin/bash',
uidNumber => '572',
gidNumber => '100',
realname => 'Alexandre Pereira dos Santos',
homeDirectory => '/home/alechand',
userPassword => 'e2NyeXB0fUpPV2hqTS9Dd2M1YnM=',
}
user { "poderoso",
loginShell => '/bin/bash',
uidNumber => '573',
gidNumber => '100',
realname => 'fabio campos poderoso',
homeDirectory => '/home/poderoso',
userPassword => 'e1NTSEF9RWxNUUtiTDBJWnVKNUFUMllzcWRpWG1KYXZJNDBqZFo=',
}
user { "ricardo",
loginShell => '/bin/bash',
uidNumber => '574',
gidNumber => '100',
realname => 'Ricardo Melo Ferreira',
homeDirectory => '/home/ricardo',
userPassword => 'e1NTSEF9UENMUERzN1FuaFFxYjhNL0NHQTNLWVQ0RmV2WWJRMzU=',
}
user { "fernanda",
loginShell => '/bin/bash',
uidNumber => '575',
gidNumber => '100',
realname => 'Fernanda Benetti',
homeDirectory => '/home/fernanda',
userPassword => 'e2NyeXB0fWcyZndoMmgxSUdwTk0=',
}
user { "jpavan",
loginShell => '/bin/bash',
uidNumber => '576',
gidNumber => '100',
realname => 'Joel Pavan',
homeDirectory => '/home/jpavan',
userPassword => 'e1NTSEF9UTF6SC9GbkRnTjJucG81eGM4RFEzSjhJSDdPNDBQSDc=',
}
user { "andrekuhn",
loginShell => '/bin/bash',
uidNumber => '577',
gidNumber => '100',
realname => 'Andre Dalpian Kuhn',
homeDirectory => '/home/andrekuhn',
userPassword => 'e1NTSEF9VFBpb2N1OUdIaEp4UisrR3FkbWcwb3JNdUdITWIrSC8=',
}
user { "jupaukowski",
loginShell => '/bin/bash',
uidNumber => '578',
gidNumber => '100',
realname => 'Juliana Zacharias Paukowski',
homeDirectory => '/home/jupaukowski',
userPassword => 'e1NTSEF9c04wOXpHTW1sbVdGV0dIL1dwY2lDTEVWMWErTUl6UFg=',
}
user { "cris",
loginShell => '/bin/bash',
uidNumber => '579',
gidNumber => '100',
realname => 'Cristina Gavazzoni',
homeDirectory => '/home/cris',
userPassword => 'e1NTSEF9WURNZkdLc1ZjdHZkd3FyaUFaRlAvcnlVdFlzM1J1WWQ=',
}
user { "guilherme",
loginShell => '/bin/bash',
uidNumber => '580',
gidNumber => '100',
realname => 'Guilherme Goncalves Ferrari',
homeDirectory => '/home/guilherme',
userPassword => 'e1NTSEF9RmtjNEMySjVlSHBVd0hNcjgyRjB0Y1pQN0ZxaEJpbEo=',
}
user { "egsouza",
loginShell => '/bin/bash',
uidNumber => '581',
gidNumber => '100',
realname => 'Everton Granemann Souza',
homeDirectory => '/home/egsouza',
userPassword => 'e1NTSEF9NEVHeTlJZHlxN0hlV2N0V3paRWFrU1ZSYmpITmFCT0I=',
}
user { "willianr",
loginShell => '/bin/bash',
uidNumber => '582',
gidNumber => '100',
realname => 'willian radunz',
homeDirectory => '/home/willianr',
userPassword => 'e1NTSEF9UmoyaU5TdVhWV053cmEwMlkyTUFZOXo1anp5cGY3MXA=',
}
user { "nep2n0",
loginShell => '/bin/bash',
uidNumber => '583',
gidNumber => '100',
realname => 'Rogelio Diaz-Mendez,Lucas,Lucas Nicolao',
homeDirectory => '/home/nep2n0',
userPassword => 'e1NTSEF9WjlrSXp5WVNKTk91UGJTb0VsZVJRZUk3azJBd3JoVHI=',
}
user { "prado",
loginShell => '/bin/bash',
uidNumber => '584',
gidNumber => '100',
realname => 'Sandra Prado',
homeDirectory => '/home/prado',
userPassword => 'e2NyeXB0fTAyRTN0ay5IT3d2eXc=',
}
user { "jocrisdias",
loginShell => '/bin/bash',
uidNumber => '585',
gidNumber => '100',
realname => 'Josiane Cristina Dias',
homeDirectory => '/home/jocrisdias',
userPassword => 'e1NTSEF9OE9mZVlpQXlIc2llaXpGdHdRNHV6OWozQ1BhQi9Cdmw=',
}
user { "riffel",
loginShell => '/bin/bash',
uidNumber => '586',
gidNumber => '100',
realname => 'Rogerio Riffel',
homeDirectory => '/home/riffel',
userPassword => 'e1NTSEF9M0tNaUtramZTZUUxUVlpYzlxVThLYzdTeGxwSWc0R1A=',
}
user { "alexp",
loginShell => '/bin/bash',
uidNumber => '587',
gidNumber => '100',
realname => 'Alex Pedroso de Moraes',
homeDirectory => '/home/alexp',
userPassword => 'e1NTSEF9NHlpQ3c4emkyWVNKcE9ZM3VXU2JuRmd2MEg4L21kbzU=',
}
user { "beatriz",
loginShell => '/bin/bash',
uidNumber => '588',
gidNumber => '100',
realname => 'Beatriz Eymi Pimentel Mizusaki',
homeDirectory => '/home/beatriz',
userPassword => 'e2NyeXB0fXQyLnZCcXlYZlRsbVE=',
}
user { "sandi",
loginShell => '/bin/bash',
uidNumber => '589',
gidNumber => '100',
realname => 'Alessandra Lutz',
homeDirectory => '/home/sandi',
userPassword => 'e2NyeXB0fW9rU1QubEJoYUxCek0=',
}
user { "vanzella",
loginShell => '/bin/bash',
uidNumber => '590',
gidNumber => '100',
realname => 'Melissa Vanzella',
homeDirectory => '/home/vanzella',
userPassword => 'e1NTSEF9OFVRcG84RG1zWDZrSFZtelNuS1c3QXg4M0NuWkNxTnk=',
}
user { "benhur",
loginShell => '/bin/bash',
uidNumber => '591',
gidNumber => '100',
realname => 'Benhur Briao',
homeDirectory => '/home/benhur',
userPassword => 'e1NTSEF9bDRUWEljZCtqek9YVVRxa3lDQVFTK1ZZM0FLRDdzOWo=',
}
user { "bordin",
loginShell => '/bin/bash',
uidNumber => '592',
gidNumber => '100',
realname => 'Jose Rafael Bordin',
homeDirectory => '/home/bordin',
userPassword => 'e2NyeXB0fXEwaHE2RkpzUEZKY1U=',
}
user { "azevedo",
loginShell => '/bin/bash',
uidNumber => '594',
gidNumber => '100',
realname => 'Gustavo de Medeiros Azevedo',
homeDirectory => '/home/azevedo',
userPassword => 'e1NTSEF9YUlYR1dVcy93M0dRN25VbU1aNzlsY3NEdTNiTjRscy8=',
}
user { "quel",
loginShell => '/bin/bash',
uidNumber => '595',
gidNumber => '100',
realname => 'Raquel Waechter',
homeDirectory => '/home/quel',
userPassword => 'e1NTSEF9ZnZGbjZ1ZWExS3A3UWdHbTBSWGVZWjJmWnBvN1FZWEo=',
}
user { "andressa",
loginShell => '/bin/bash',
uidNumber => '596',
gidNumber => '100',
realname => 'Andressa Antonini Bertolazzo',
homeDirectory => '/home/andressa',
userPassword => 'e2NyeXB0fTdjTTdPQ0pQWXc3ZGM=',
}
user { "krott",
loginShell => '/bin/bash',
uidNumber => '597',
gidNumber => '100',
realname => 'Leandro Krott',
homeDirectory => '/home/krott',
userPassword => 'e2NyeXB0fTIxWU5udHhwNlg2OG8=',
}
user { "perrone",
loginShell => '/bin/bash',
uidNumber => '598',
gidNumber => '100',
realname => 'Gabriel Cury Perrone',
homeDirectory => '/home/perrone',
userPassword => 'e2NyeXB0fWM0S3VCRTk4MER3WTI=',
}
user { "tgarcia",
loginShell => '/bin/bash',
uidNumber => '599',
gidNumber => '100',
realname => 'Thomas Garcia',
homeDirectory => '/home/tgarcia',
userPassword => 'e1NTSEF9a3Z2a0dNMFVxMWZrQ0RyT1h6bDFaRmpOcmFGekIwN2s=',
}
user { "lucianoborba",
loginShell => '/bin/bash',
uidNumber => '600',
gidNumber => '100',
realname => 'lucianoborba',
homeDirectory => '/home/lucianoborba',
userPassword => 'e1NTSEF9UTZ6WERPL1lEYWkvMjBzczRibU42NzVQbjRvV1g1aTI=',
}
user { "rdasilva",
loginShell => '/bin/bash',
uidNumber => '602',
gidNumber => '100',
realname => 'Roberto da Silva',
homeDirectory => '/home/rdasilva',
userPassword => 'e2NyeXB0fS9vZTFoM282RlQ4Sm8=',
}
user { "francovalduga",
loginShell => '/bin/bash',
uidNumber => '603',
gidNumber => '100',
realname => 'Franco Valduga, 00129844, M206',
homeDirectory => '/home/francovalduga',
userPassword => 'e2NyeXB0fVBMTE4vV1o1c0h3b2c=',
}
user { "lbpiovesan",
loginShell => '/bin/bash',
uidNumber => '604',
gidNumber => '100',
realname => 'Laura Bottin Piovesan, 182639, N211',
homeDirectory => '/home/lbpiovesan',
userPassword => 'e1NTSEF9VXc1NnZVZjBuNmxHMy94ZjV3S05QeXRvTjBodURkQ0Y=',
}
user { "mrsilva",
loginShell => '/bin/bash',
uidNumber => '605',
gidNumber => '100',
realname => 'Marcos Rodrigo da Silva',
homeDirectory => '/home/mrsilva',
userPassword => 'e2NyeXB0fUxQRC5Pa055VWNqVFk=',
}
user { "rbarbosa",
loginShell => '/bin/bash',
uidNumber => '606',
gidNumber => '100',
realname => 'Rafael de Carvalho Barbosa, 255144, M205',
homeDirectory => '/home/rbarbosa',
userPassword => 'e2NyeXB0fVVXNTdNUUdRR2t1VEU=',
}
user { "lauraprandi",
loginShell => '/bin/bash',
uidNumber => '607',
gidNumber => '100',
realname => 'Laura Prandi',
homeDirectory => '/home/lauraprandi',
userPassword => 'e2NyeXB0fUlEajhyOEZkeXVhQjI=',
}
user { "jardel',
loginShell => '/bin/bash',
uidNumber => '609',
gidNumber => '100',
realname => 'Jardel Cestari, M208',
homeDirectory => '/home/jardel',
userPassword => 'e2NyeXB0fW9GNE9xSk8yVFU5ZUk=',
}
user { "dfrydel",
loginShell => '/bin/bash',
uidNumber => '610',
gidNumber => '100',
realname => 'Derek Frydel, Salas dos Post-docs predio N',
homeDirectory => '/home/dfrydel',
userPassword => 'e2NyeXB0fU04YnpIcVBCYkg0S2s=',
}
user { "zigue",
loginShell => '/bin/bash',
uidNumber => '611',
gidNumber => '100',
realname => 'Gabriel Zigue, M216, 136489',
homeDirectory => '/home/zigue',
userPassword => 'e2NyeXB0fVFXVDl2TEwzTWdNV00=',
}
user { "zezo",
loginShell => '/bin/bash',
uidNumber => '612',
gidNumber => '100',
realname => 'Jose Luiz Ferreira Jr, 151721, M208, Ramal 6504',
homeDirectory => '/home/zezo',
userPassword => 'e2NyeXB0fVk1OFQubWRnaW9aazY=',
}
user { "furlan",
loginShell => '/bin/bash',
uidNumber => '613',
gidNumber => '100',
realname => 'Alexandre Penteado Furlan, M205',
homeDirectory => '/home/furlan',
userPassword => 'e2NyeXB0fUQ2bFRvTDJ0bnhUMFE=',
}
user { "tekkito",
loginShell => '/bin/bash',
uidNumber => '614',
gidNumber => '100',
realname => 'Raphael Imbuzeiro, 209040, L205',
homeDirectory => '/home/tekkito',
userPassword => 'e2NyeXB0fTI1YTByVmk4TlRFRmM=',
}
user { "pablovalverde",
loginShell => '/bin/bash',
uidNumber => '615',
gidNumber => '100',
realname => 'Pablo Valverde, 196321, N207',
homeDirectory => '/home/pablovalverde',
userPassword => 'e2NyeXB0fTFORlR5OEZOMjQ2Ync=',
}
user { "maximiliano",
loginShell => '/bin/bash',
uidNumber => '616',
gidNumber => '100',
realname => 'Maximiliano Jesus Moreno Zapata, PG, Lab. Durao',
homeDirectory => '/home/maximiliano',
userPassword => 'e2NyeXB0fTIwcS5kbHJCNzBQOTY=',
}
user { "ambotelho",
loginShell => '/bin/bash',
uidNumber => '617',
gidNumber => '100',
realname => 'Ataides Martins Botelho Neto, 00204825, M216',
homeDirectory => '/home/ambotelho',
userPassword => 'e2NyeXB0fTFxUDZRMmIvTllRYUE=',
}
user { "mendeli",
loginShell => '/bin/bash',
uidNumber => '618',
gidNumber => '100',
realname => 'Mendeli Vainstein, 94554, N206 6474',
homeDirectory => '/home/mendeli',
userPassword => 'e2NyeXB0fXc0Zk5mbVNwTE56SHc=',
}
user { "creq",
loginShell => '/bin/bash',
uidNumber => '619',
gidNumber => '100',
realname => 'Carlo Requiao, N114',
homeDirectory => '/home/creq',
userPassword => 'e2NyeXB0fTR2MmJGSFY1RUNiOGs=',
}
user { "nmallmann",
loginShell => '/bin/bash',
uidNumber => '620',
gidNumber => '100',
realname => 'Nicolas Mallmann, 150253, Lab. Microeletronica',
homeDirectory => '/home/nmallmann',
userPassword => 'e2NyeXB0fURwVC5aLk51WjJpMy4=',
}
user { "anacarol",
loginShell => '/bin/bash',
uidNumber => '621',
gidNumber => '100',
realname => 'Ana Carolina Ribeiro Teixeira, 80243020, N224',
homeDirectory => '/home/anacarol',
userPassword => 'e2NyeXB0fTRScHZrb2lMeXZaQWc=',
}
user { "doria",
loginShell => '/bin/bash',
uidNumber => '623',
gidNumber => '100',
realname => 'Felipe Franca Doria, Aluno PG, Orientador Rubem Erichsen',
homeDirectory => '/home/doria',
userPassword => 'e2NyeXB0fVl1YzB4V2dRTUtET3c=',
}
user { "michou",
loginShell => '/bin/bash',
uidNumber => '624',
gidNumber => '100',
realname => 'Charlotte Rulquin, N210',
homeDirectory => '/home/michou',
userPassword => 'e2NyeXB0fWdIa25RZVcwbkt5Y1U=',
}
user { "marcelo13",
loginShell => '/bin/bash',
uidNumber => '625',
gidNumber => '100',
realname => 'Marcelo Castaneda, M202, 6496',
homeDirectory => '/home/marcelo13',
userPassword => 'e2NyeXB0fVFBbUQweUlwL0RnMmc=',
}
user { "thalestr",
loginShell => '/bin/bash',
uidNumber => '626',
gidNumber => '100',
realname => 'Thales Marques Correa da Silva, 00159543, M206',
homeDirectory => '/home/thalestr',
userPassword => 'e2NyeXB0fTZRZDlLWDdUZXc5cVk=',
}
user { "daniel",
loginShell => '/bin/bash',
uidNumber => '627',
gidNumber => '100',
realname => 'Daniel de Oliveira Berto,  171711,  34937580',
homeDirectory => '/home/daniel',
userPassword => 'e1NTSEF9TkFSeTJXNklXb1IyaWpXd25mWVlGNmtVc3pCYnRLMkM=',
}
user { "michou2",
loginShell => '/bin/bash',
uidNumber => '628',
gidNumber => '100',
realname => 'Charlotte Rulquin, N214',
homeDirectory => '/home/michou2',
userPassword => 'e1NTSEF9UW94S1FBeFhXbEtidE9HcklHRXYySmwvM01WRm0yZk0=',
}
user { "alan",
loginShell => '/bin/bash',
uidNumber => '629',
gidNumber => '100',
realname => 'Alan Barros de Oliveira',
homeDirectory => '/home/alan',
userPassword => 'e1NTSEF9OTNpUmYzcHpZcVM0WDhvRFBJNmc0eWxwVm9Pa0doOWo=',
}
user { "ruben.carvalho",
loginShell => '/bin/bash',
uidNumber => '630',
gidNumber => '100',
realname => 'Rubens Carvalho, M207',
homeDirectory => '/home/ruben.carvalho',
userPassword => 'e1NTSEF9RkhBMVZuNy8xOFNDVk51c2JWOXVsaTF3ZVhDT3hvVVo=',
}
user { "rubens.carvalho",
loginShell => '/bin/bash',
uidNumber => '631',
gidNumber => '100',
realname => 'Rubens Carvalho, M207',
homeDirectory => '/home/rubens.carvalho',
userPassword => 'e2NyeXB0fUsvc0xlR2s5VEhrVXM=',
}
user { "vquadros",
loginShell => '/bin/bash',
uidNumber => '632',
gidNumber => '100',
realname => 'Vanessa Quadros, PG',
homeDirectory => '/home/vquadros',
userPassword => 'e2NyeXB0fVQ1WmhVbkovY2MvZW8=',
}
user { "cassiok",
loginShell => '/bin/bash',
uidNumber => '633',
gidNumber => '100',
realname => 'Cassio, Bolsista Setor Informatica',
homeDirectory => '/home/cassiok',
userPassword => 'e2NyeXB0fWQzeWMxbUJBeUpmLms=',
}
user { "luna",
loginShell => '/bin/bash',
uidNumber => '634',
gidNumber => '100',
realname => 'Emerson Luna, 00213406, casarosada310',
homeDirectory => '/home/luna',
userPassword => 'e2NyeXB0fUVoQWZnTUZwSTdpZS4=',
}
user { "broilo",
loginShell => '/bin/bash',
uidNumber => '635',
gidNumber => '100',
realname => 'Mateus Broilo',
homeDirectory => '/home/broilo',
userPassword => 'e2NyeXB0fWVxb0lXaHdLeVROWmM=',
}
user { "mlsilvestrini",
loginShell => '/bin/bash',
uidNumber => '636',
gidNumber => '100',
realname => 'Marion Silvestrini, 208620',
homeDirectory => '/home/mlsilvestrini',
userPassword => 'e2NyeXB0fXl0bFRONEtiS1NheC4=',
}
