Vagrant.configure("2") do |config|
 config.vm.box = "wheezy64"
   projeto = 'cluster_torque'
   rede_externa =
   rede_mpi = '192.168.1'
   rede_nfs = '10.1.0'

 
  # Integracao Puppet 
  config.vm.provision :puppet do |puppet|
    puppet.manifests_path = "../puppet/manifests"
    puppet.manifest_file = "cluster.pp"
    puppet.module_path = "../puppet/modules"
    puppet.options << '--fileserverconfig /vagrant/fileserver.conf'
  end

  config.vm.provider :virtualbox do |vb|
    vb.gui = false
    vb.customize ['modifyvm', :id, '--memory', 1024]
    vb.customize ['modifyvm', :id, '--cpus', 2]
    vb.customize ['modifyvm', :id, '--cpuexecutioncap', 90]
  end

  config.vm.define :ada do |ada|
    ada.vm.hostname = 'ada'
    ada.vm.network :private_network, ip: rede_mpi+'.254'
    ada.vm.network :private_network, ip: rede_nfs+'.254'
  end

end
